# Generated by Django 4.2.7 on 2023-11-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_alter_usuariocliente_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.cliente'),
        ),
    ]
