# Generated by Django 4.2.7 on 2023-11-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_alter_usuariocliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='tipoclienteid',
            field=models.ForeignKey(blank=True, db_column='TipoClienteID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.tiposcliente'),
        ),
    ]
