# Generated by Django 4.2.7 on 2023-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0007_usuariocliente_tipoclienteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='fotoUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
