# Generated by Django 4.2.7 on 2023-12-09 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0008_usuariocliente_fotourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.empleado'),
        ),
    ]
