# Generated by Django 4.2.7 on 2023-12-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0009_usuariocliente_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='esEmpleado',
            field=models.BooleanField(default=False),
        ),
    ]
