# Generated by Django 4.2.7 on 2023-12-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0010_usuariocliente_esempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='fotoUrl',
            field=models.TextField(blank=True, default='https://i.imgur.com/Y7PJdJh.jpg', null=True),
        ),
    ]
