# Generated by Django 4.2.7 on 2023-11-24 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marcastarjeta',
            table='Marcastarjeta',
        ),
        migrations.AlterModelTable(
            name='tiposcliente',
            table='Tiposcliente',
        ),
    ]
