# Generated by Django 4.2.7 on 2023-11-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_tiposcliente_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposcliente',
            options={'managed': True},
        ),
    ]
