# Generated by Django 4.2.7 on 2023-11-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_tiposcliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposcliente',
            options={'managed': False},
        ),
    ]
