# Generated by Django 4.2.7 on 2023-11-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_tiposcliente_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiposcliente',
            table='Tiposcliente',
        ),
    ]
