# Generated by Django 4.2.7 on 2023-11-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_tiposcliente_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriaCuenta',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.DeleteModel(
            name='Direcciones',
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='Marcastarjeta',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
        migrations.DeleteModel(
            name='Tiposcliente',
        ),
    ]
